<?php
$config->custom->session['blowfish'] = '6863651baf84d300a6b367cf69977c0a';  # Autogenerated for LDAP01.NOC.HEXUNIDC.COM

$config->custom->appearance['friendly_attrs'] = array(
	'facsimileTelephoneNumber' => 'Fax',
	'gid'                      => 'Group',
	'mail'                     => 'Email',
	'telephoneNumber'          => 'Telephone',
	'uid'                      => 'User Name',
	'userPassword'             => 'Password'
);

$servers = new Datastore();

$servers->newServer('ldap_pla');
$servers->setValue('server','name','ldap.noc.aiuv.com');
$servers->setValue('server','host','127.0.0.1');
$servers->setValue('server','port',389);
$servers->setValue('server','base',array('dc=noc,dc=aiuv,dc=com'));
$servers->setValue('login','auth_type','cookie');
$servers->setValue('login','bind_id','');
$servers->setValue('login','bind_pass','');
$servers->setValue('server','tls',false);
?>
